### ISSUE TITLE
Refused to execute script from '*.worker.ts' because its MIME type ('(null)/ts') is not executable, and strict MIME type checking is enabled

### ISSUE THREAD

**Issue by vcsavinash** [itsjohncs/vite-plugin-prebundle-workers#1]
Tried using the plugin in Vite based Vue 3 project. Getting the following error:
`Refused to execute script from '*.worker.ts' because its MIME type ('(null)/ts') is not executable, and strict MIME type checking is enabled.`

The code is as below:
```
private baseUrl = import.meta.url;
public persistWorker = new Worker(new URL('./*.worker.ts', this.baseUrl));
```
Why does this error thrown?

**Comment by itsjohncs** [comment]
MIME types aren’t controlled by this plugin, so I’m not exactly sure what’s causing that in your setup but you can’t use a wildcard in a worker URL AFAIK. I’m at  least unsure of what that will do. Try with a specific file name like `./myFile.worker.ts`.
